# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Testmeetmin' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Testmeetmin
    pod 'AWSCore', '~> 2.12.0'
    pod 'AWSMobileClient', '~> 2.12.0'      # Required dependency
    pod 'AWSAuthUI', '~> 2.12.0'            # Optional dependency required to use drop-in UI
    pod 'AWSUserPoolsSignIn', '~> 2.12.0'
end
