# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Amp2' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Amp2
  pod 'AWSCore', '~> 2.11.0'
  pod 'AWSMobileClient', '~> 2.11.0'      # Required dependency
  pod 'AWSAuthUI', '~> 2.11.0'            # Optional dependency required to use drop-in UI
  pod 'AWSUserPoolsSignIn', '~> 2.11.0'   


end
